baseurl = "https://www.007ffflearning.com"
title = "Azure Readiness starts here..."
theme = "cleanwhite"
publishDir = "docs"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 7 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  author = "Peter De Tender"
  header_image = "img/home-bg-azure.jpg"
  SEOTitle = "Azure Readiness Starts Here"
  slogan = "The best way to know the future, is to learn it"
  keyword = "Azure, Learning, Certification, Technology"
  accent = "#007FFF"
  

  image_404 = "img/404-bg.jpg"
  title_404 = "Looks like what you are looking for is not here for the moment"
  omit_categories = false

  # algolia site search
  algolia_search = false
  #algolia_appId = ""
  #algolia_indexName = ""
  #algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Bring me an audience, I'll give them Azure knowledge in return"
  sidebar_avatar = "img/007ffflearning-ape.png"      

  featured_tags = true 
  featured_condition_size = 1 

  friends = false
  bookmarks = true
  about_me = true

  [params.social]
  rss            = true 
  email          = "info@007ffflearning.com"
  #facebook      = "http://www.facebook.com/pdtit"
  twitter       = "http://www.twitter.com/pdtit"
  linkedin       = "https://www.linkedin.com/in/pdtit/"
  github         = "https://github.com/007ffflearning"
    
  ##[[params.friend_link]]
  ##title = "Linda的博客"
  ##href =  "https://zhaozhihan.com"

  ## list up the bookmark URLs here
  [[params.bookmark_link]]
  title =  "Azure Portal"
  href =  "https://portal.azure.com"
  [[params.bookmark_link]]
  title = "Azure Documentation"
  href =  "http://docs.microsoft.com/en-us/azure"
  [[params.bookmark_link]]
  title =  "MC2MC"
  href = "https://www.mc2mc.be"
 
  
  [[params.addtional_menus]]
  title =  "Azure HOL"
  href =  "/azurehol/"
  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/books/"
  [[params.addtional_menus]]
  title =  "VIDEOS"
  href =  "/videos/"
  [[params.addtional_menus]]
  title =  "ABOUT ME"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
